### ISSUE TITLE
Scale accordion label with screen size

### ISSUE THREAD

**Issue by jackturnbull** [sky-uk/toolkit-ui#164]
## Expected Behavior

When scaling up the screen size, the accordion label should also scale. The static text size can look jarring against the tile text size at larger screen sizes.

Prevalent on:
* https://www.sky.com/help
* https://www.sky.com/mysky

## Current Behavior

Text size does not scale, causing a small accordion text size when seen against the scaling tile size. Examples:

![screen shot 2016-09-27 at 12 00 39](https://cloud.githubusercontent.com/assets/3958636/18870750/108edace-84aa-11e6-8569-98e677e0f2ed.png)
![screen shot 2016-09-27 at 12 00 54](https://cloud.githubusercontent.com/assets/3958636/18870749/108cc392-84aa-11e6-8965-a7d7177dd325.png)

## Possible Solution

Use relative text sizes, or media queries to increase font size at larger screen sized.

It may be the case that the toolkit is not the appropriate place for this, as all accordions may not need to scale - if not then we could pass a class through to allow for scaling of text sized (or implement on each accordion).

## Steps to Reproduce (for bugs)

Visit:
* https://www.sky.com/help
* https://www.sky.com/mysky

Scroll to bottom

## Your Environment

* Sky-Pages live
* Toolkit latest
* Chrome latest

**Comment by joebell93** [comment]
@jackturnbull cheers for the detailed issue and description! 

Unfortunately this a problem unique to Sky Pages and how their Tiles are handled - so I'm going to close this for now.

Design elements shouldn't really be handled relatively, Tiles are an exception due to the content being restricted to a fixed height. If Tiles are kept in a container, this shouldn't be a problem going forwards.

---

cc'ing @MrDinsdale who's currently working on Toolkit Tile integration within Sky Pages, could be worth chatting with him

**Comment by jackturnbull** [comment]
Cool, cheers for the explanation mate! If tiles are the exception then it seems like we need a way of handling those - possibly in a container as you say rather than forcing other elements to be relative.

I can see this also being an issue in other page templates that require text so I'd be interested in chatting through that one also!
